#!/bin/bash
set -euo pipefail

# =============================================================
# OpenClaw PaaS - One-Click Deployment Script
# =============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFESTS_DIR="${SCRIPT_DIR}/k8s-manifests"
WIZARD_DIR="${SCRIPT_DIR}/setup-wizard"
CF_CONFIG="${SCRIPT_DIR}/cf-config.json"
NAMESPACE="openclaw-tenant-1"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

echo "============================================================"
echo "  OpenClaw PaaS - Tenant Deployment"
echo "============================================================"
echo ""

# ─────────────────────────────────────────────────
# Step 0: Validate prerequisites
# ─────────────────────────────────────────────────
info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || fail "docker is not installed."
command -v kubectl >/dev/null 2>&1 || fail "kubectl is not installed."

if [ ! -f "${CF_CONFIG}" ]; then
    fail "cf-config.json not found. Run 'python3 init-cloudflare.py' first."
fi

# Parse Cloudflare config
CF_API_TOKEN=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_API_TOKEN'])")
CF_TUNNEL_TOKEN=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_TUNNEL_TOKEN'])")
CF_ACCOUNT_ID=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_ACCOUNT_ID'])")
CF_TUNNEL_ID=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_TUNNEL_ID'])")
DOMAIN=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['DOMAIN'])")

ok "Prerequisites validated."
echo ""

# ─────────────────────────────────────────────────
# Step 1: Build Setup Wizard Docker image
# ─────────────────────────────────────────────────
info "Building Setup Wizard Docker image..."
docker build -t openclaw-setup-wizard:latest "${WIZARD_DIR}"
ok "Docker image built: openclaw-setup-wizard:latest"
echo ""

# ─────────────────────────────────────────────────
# Step 2: Import image into K3s containerd
# ─────────────────────────────────────────────────
info "Importing image into K3s..."
docker save openclaw-setup-wizard:latest | sudo k3s ctr images import -
ok "Image imported into K3s."
echo ""

# ─────────────────────────────────────────────────
# Step 3: Apply namespace first
# ─────────────────────────────────────────────────
info "Creating namespace..."
kubectl apply -f "${MANIFESTS_DIR}/00-namespace.yaml"
ok "Namespace '${NAMESPACE}' ready."
echo ""

# ─────────────────────────────────────────────────
# Step 4: Generate and apply K8s Secrets from cf-config.json
# ─────────────────────────────────────────────────
info "Generating K8s Secrets from Cloudflare config..."

CF_API_TOKEN_B64=$(echo -n "${CF_API_TOKEN}" | base64 -w0)
CF_TUNNEL_TOKEN_B64=$(echo -n "${CF_TUNNEL_TOKEN}" | base64 -w0)

cat > "${MANIFESTS_DIR}/02-secrets.yaml" <<EOYAML
# Auto-generated by deploy.sh - DO NOT commit to version control
apiVersion: v1
kind: Secret
metadata:
  name: cf-secrets
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: openclaw-paas
type: Opaque
data:
  CF_API_TOKEN: "${CF_API_TOKEN_B64}"
  CF_TUNNEL_TOKEN: "${CF_TUNNEL_TOKEN_B64}"
EOYAML

kubectl apply -f "${MANIFESTS_DIR}/02-secrets.yaml"
ok "K8s Secret 'cf-secrets' created."
echo ""

# ─────────────────────────────────────────────────
# Step 5: Configure initial Cloudflare Tunnel route → Setup Wizard
# ─────────────────────────────────────────────────
info "Configuring Cloudflare Tunnel to point to Setup Wizard..."
ROUTE_RESPONSE=$(curl -s -X PUT \
    "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/cfd_tunnel/${CF_TUNNEL_ID}/configurations" \
    -H "Authorization: Bearer ${CF_API_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "{\"config\":{\"ingress\":[{\"hostname\":\"${DOMAIN}\",\"service\":\"http://setup-wizard-svc:18790\"},{\"service\":\"http_status:404\"}]}}")

ROUTE_SUCCESS=$(echo "${ROUTE_RESPONSE}" | python3 -c "import sys,json; print(json.load(sys.stdin).get('success','false'))" 2>/dev/null || echo "false")
if [ "${ROUTE_SUCCESS}" = "True" ] || [ "${ROUTE_SUCCESS}" = "true" ]; then
    ok "Cloudflare Tunnel route configured: ${DOMAIN} → setup-wizard-svc:18790"
else
    warn "Cloudflare route config may have failed. Response: ${ROUTE_RESPONSE}"
fi
echo ""

# ─────────────────────────────────────────────────
# Step 6: Apply all remaining K8s manifests
# ─────────────────────────────────────────────────
info "Applying K8s manifests..."
kubectl apply -f "${MANIFESTS_DIR}/"
ok "All manifests applied."
echo ""

# ─────────────────────────────────────────────────
# Step 7: Verify deployment status
# ─────────────────────────────────────────────────
info "Verifying deployment status..."
echo ""
echo "  Deployments:"
kubectl get deployments -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""
echo "  Services:"
kubectl get svc -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""
echo "  Pods:"
kubectl get pods -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""

echo "============================================================"
ok "Deployment complete!"
echo ""
echo "  Domain: https://${DOMAIN}"
echo "  Setup Wizard is running and waiting for user configuration."
echo "  Visit the domain above to begin OpenClaw setup."
echo "============================================================"
