#!/bin/bash
set -euo pipefail

# =============================================================
# Odoo 18 — Deployment Script for Mark Studio (markstudio-odoo)
#
# Deploys Odoo 18 into a dedicated K8s namespace using the
# existing Cloudflare Tunnel from openclaw-tenant-1.
#
# Prerequisites:
#   - K3s cluster running
#   - kubectl configured
#   - cf-config.json exists (from init-cloudflare.py)
#   - python3 + requests installed (for Cloudflare API)
# =============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFESTS_DIR="${SCRIPT_DIR}/odoo-k8s-manifests"
CF_CONFIG="${SCRIPT_DIR}/cf-config.json"
NAMESPACE="markstudio-odoo"
ODOO_DOMAIN="markstudio-odoo.woowtech.io"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

echo "============================================================"
echo "  Mark Studio — Odoo 18 Deployment"
echo "  Domain: https://${ODOO_DOMAIN}"
echo "============================================================"
echo ""

# ─────────────────────────────────────────────────
# Step 0: Validate prerequisites
# ─────────────────────────────────────────────────
info "Checking prerequisites..."

command -v kubectl >/dev/null 2>&1 || fail "kubectl is not installed."
command -v python3 >/dev/null 2>&1 || fail "python3 is not installed."

if [ ! -f "${CF_CONFIG}" ]; then
    fail "cf-config.json not found. Run 'python3 init-cloudflare.py' first."
fi

if [ ! -d "${MANIFESTS_DIR}" ]; then
    fail "odoo-k8s-manifests/ directory not found."
fi

# Parse Cloudflare config (shared with OpenClaw)
CF_API_TOKEN=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_API_TOKEN'])")
CF_ACCOUNT_ID=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_ACCOUNT_ID'])")

# Detect the actual tunnel ID from the running cloudflared's K8s secret
# (cf-config.json may have a different tunnel than the one actually deployed)
CF_TUNNEL_ID=$(kubectl get secret cf-secrets -n openclaw-tenant-1 \
    -o jsonpath='{.data.CF_TUNNEL_TOKEN}' 2>/dev/null \
    | base64 -d \
    | python3 -c "import sys,json,base64; t=sys.stdin.read(); d=json.loads(base64.b64decode(t+'==')); print(d['t'])" 2>/dev/null)

if [ -z "${CF_TUNNEL_ID}" ]; then
    warn "Could not detect tunnel ID from K8s secret, falling back to cf-config.json"
    CF_TUNNEL_ID=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_TUNNEL_ID'])")
fi

info "Using Tunnel ID: ${CF_TUNNEL_ID}"

ok "Prerequisites validated."
echo ""

# ─────────────────────────────────────────────────
# Step 1: Create namespace
# ─────────────────────────────────────────────────
info "Creating namespace '${NAMESPACE}'..."
kubectl apply -f "${MANIFESTS_DIR}/00-namespace.yaml"
ok "Namespace '${NAMESPACE}' ready."
echo ""

# ─────────────────────────────────────────────────
# Step 2: Generate and apply K8s Secrets
# ─────────────────────────────────────────────────
info "Generating Odoo secrets..."

# Check if secrets already exist (don't overwrite on re-deploy)
if kubectl get secret odoo-secrets -n "${NAMESPACE}" >/dev/null 2>&1; then
    warn "Secret 'odoo-secrets' already exists — skipping generation."
    warn "To regenerate: kubectl delete secret odoo-secrets -n ${NAMESPACE}"
else
    POSTGRES_PW=$(openssl rand -base64 24)
    ADMIN_PW=$(openssl rand -base64 24)

    POSTGRES_PW_B64=$(echo -n "${POSTGRES_PW}" | base64 -w0)
    ADMIN_PW_B64=$(echo -n "${ADMIN_PW}" | base64 -w0)

    cat > "${MANIFESTS_DIR}/01-secrets.yaml" <<EOYAML
# Auto-generated by odoo-deploy.sh — DO NOT commit to version control
apiVersion: v1
kind: Secret
metadata:
  name: odoo-secrets
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: markstudio-odoo
type: Opaque
data:
  POSTGRES_PASSWORD: "${POSTGRES_PW_B64}"
  ODOO_ADMIN_PASSWORD: "${ADMIN_PW_B64}"
EOYAML

    kubectl apply -f "${MANIFESTS_DIR}/01-secrets.yaml"

    echo ""
    echo "  ┌─────────────────────────────────────────────┐"
    echo "  │  SAVE THESE CREDENTIALS — shown only once   │"
    echo "  ├─────────────────────────────────────────────┤"
    echo "  │  PostgreSQL Password: ${POSTGRES_PW}"
    echo "  │  Odoo Admin Password: ${ADMIN_PW}"
    echo "  └─────────────────────────────────────────────┘"
    echo ""
    ok "Secret 'odoo-secrets' created."
fi
echo ""

# ─────────────────────────────────────────────────
# Step 3: Apply all K8s manifests
# ─────────────────────────────────────────────────
info "Applying K8s manifests..."
kubectl apply -f "${MANIFESTS_DIR}/"
ok "All manifests applied."
echo ""

# ─────────────────────────────────────────────────
# Step 4: Add Cloudflare Tunnel route (read-modify-write)
#
# CRITICAL: The Cloudflare tunnel PUT API replaces the ENTIRE
# ingress array. We must GET current config, insert the Odoo
# hostname, then PUT the complete updated config — otherwise
# existing OpenClaw routes will be destroyed.
# ─────────────────────────────────────────────────
info "Configuring Cloudflare Tunnel route for ${ODOO_DOMAIN}..."

python3 - "${CF_API_TOKEN}" "${CF_ACCOUNT_ID}" "${CF_TUNNEL_ID}" "${ODOO_DOMAIN}" <<'PYEOF'
import json, sys, requests

CF_API_TOKEN = sys.argv[1]
CF_ACCOUNT_ID = sys.argv[2]
CF_TUNNEL_ID = sys.argv[3]
ODOO_DOMAIN = sys.argv[4]
ODOO_SERVICE = "http://odoo-web-svc.markstudio-odoo.svc.cluster.local:8069"

BASE = "https://api.cloudflare.com/client/v4"
HEADERS = {
    "Authorization": f"Bearer {CF_API_TOKEN}",
    "Content-Type": "application/json",
}

# Step 4a: GET current tunnel configuration
print(f"  [4a] Fetching current tunnel config...")
resp = requests.get(
    f"{BASE}/accounts/{CF_ACCOUNT_ID}/cfd_tunnel/{CF_TUNNEL_ID}/configurations",
    headers=HEADERS,
)
resp.raise_for_status()
data = resp.json()

if not data.get("success"):
    print(f"  [ERROR] Failed to fetch tunnel config: {data}")
    sys.exit(1)

current_config = data.get("result", {}).get("config", {})
ingress = current_config.get("ingress", [])
print(f"  [4a] Current ingress has {len(ingress)} rules")

# Step 4b: Check if Odoo route already exists
odoo_exists = any(
    rule.get("hostname") == ODOO_DOMAIN
    for rule in ingress
)

if odoo_exists:
    print(f"  [4b] Route for {ODOO_DOMAIN} already exists — skipping.")
    sys.exit(0)

# Step 4c: Insert Odoo route BEFORE the catch-all (last entry)
# The last entry is always {"service": "http_status:404"} (no hostname)
new_rule = {
    "hostname": ODOO_DOMAIN,
    "service": ODOO_SERVICE,
}

# Insert before the last catch-all rule
if ingress and "hostname" not in ingress[-1]:
    # Last rule is the catch-all — insert before it
    ingress.insert(-1, new_rule)
else:
    # No catch-all found — append rule + catch-all
    ingress.append(new_rule)
    ingress.append({"service": "http_status:404"})

print(f"  [4c] New ingress has {len(ingress)} rules:")
for i, rule in enumerate(ingress):
    hostname = rule.get("hostname", "(catch-all)")
    service = rule.get("service", "?")
    print(f"        [{i}] {hostname} → {service}")

# Step 4d: PUT updated tunnel configuration
print(f"  [4d] Updating tunnel configuration...")
updated_config = {"config": {"ingress": ingress}}
resp = requests.put(
    f"{BASE}/accounts/{CF_ACCOUNT_ID}/cfd_tunnel/{CF_TUNNEL_ID}/configurations",
    headers=HEADERS,
    json=updated_config,
)
resp.raise_for_status()
result = resp.json()

if result.get("success"):
    print(f"  [4d] Tunnel route configured: {ODOO_DOMAIN} → {ODOO_SERVICE}")
else:
    print(f"  [ERROR] Failed to update tunnel config: {result}")
    sys.exit(1)
PYEOF

ROUTE_EXIT=$?
if [ "${ROUTE_EXIT}" -eq 0 ]; then
    ok "Cloudflare Tunnel route configured."
else
    warn "Cloudflare route configuration may have failed (exit code ${ROUTE_EXIT})."
fi
echo ""

# ─────────────────────────────────────────────────
# Step 5: Create DNS CNAME record
# ─────────────────────────────────────────────────
info "Creating DNS CNAME record for ${ODOO_DOMAIN}..."

python3 - "${CF_API_TOKEN}" "${CF_TUNNEL_ID}" "${ODOO_DOMAIN}" <<'PYEOF'
import json, sys, requests

CF_API_TOKEN = sys.argv[1]
CF_TUNNEL_ID = sys.argv[2]
ODOO_DOMAIN = sys.argv[3]

BASE = "https://api.cloudflare.com/client/v4"
HEADERS = {
    "Authorization": f"Bearer {CF_API_TOKEN}",
    "Content-Type": "application/json",
}

# Get zone for the domain (woowtech.io)
# Extract parent domain: markstudio-odoo.woowtech.io → woowtech.io
parts = ODOO_DOMAIN.split(".")
parent_domain = ".".join(parts[-2:])

print(f"  [5a] Looking up zone for {parent_domain}...")
resp = requests.get(
    f"{BASE}/zones?name={parent_domain}",
    headers=HEADERS,
)
resp.raise_for_status()
zones = resp.json().get("result", [])

if not zones:
    print(f"  [WARN] Zone '{parent_domain}' not found. Create CNAME manually:")
    print(f"         {ODOO_DOMAIN} → {CF_TUNNEL_ID}.cfargotunnel.com")
    sys.exit(0)

zone_id = zones[0]["id"]
print(f"  [5a] Zone ID: {zone_id}")

# Check if CNAME already exists
print(f"  [5b] Checking for existing DNS record...")
resp = requests.get(
    f"{BASE}/zones/{zone_id}/dns_records?name={ODOO_DOMAIN}&type=CNAME",
    headers=HEADERS,
)
resp.raise_for_status()
records = resp.json().get("result", [])

cname_target = f"{CF_TUNNEL_ID}.cfargotunnel.com"

if records:
    record_id = records[0]["id"]
    print(f"  [5b] CNAME already exists (id={record_id}) — updating...")
    resp = requests.put(
        f"{BASE}/zones/{zone_id}/dns_records/{record_id}",
        headers=HEADERS,
        json={
            "type": "CNAME",
            "name": ODOO_DOMAIN,
            "content": cname_target,
            "proxied": True,
            "ttl": 1,
        },
    )
else:
    print(f"  [5b] Creating new CNAME record...")
    resp = requests.post(
        f"{BASE}/zones/{zone_id}/dns_records",
        headers=HEADERS,
        json={
            "type": "CNAME",
            "name": ODOO_DOMAIN,
            "content": cname_target,
            "proxied": True,
            "ttl": 1,
        },
    )

resp.raise_for_status()
result = resp.json()
if result.get("success"):
    print(f"  [5c] DNS CNAME: {ODOO_DOMAIN} → {cname_target} (proxied)")
else:
    print(f"  [WARN] DNS record may have failed: {result}")
PYEOF

DNS_EXIT=$?
if [ "${DNS_EXIT}" -eq 0 ]; then
    ok "DNS CNAME record configured."
else
    warn "DNS record creation may have failed."
fi
echo ""

# ─────────────────────────────────────────────────
# Step 6: Wait for pods and verify
# ─────────────────────────────────────────────────
info "Waiting for pods to be ready (up to 120s)..."
kubectl wait --for=condition=Ready pod -l app=odoo-db -n "${NAMESPACE}" --timeout=120s 2>/dev/null || \
    warn "PostgreSQL pod not ready within 120s — check logs."
kubectl wait --for=condition=Ready pod -l app=odoo -n "${NAMESPACE}" --timeout=180s 2>/dev/null || \
    warn "Odoo pod not ready within 180s — check logs."
echo ""

# ─────────────────────────────────────────────────
# Step 7: Show deployment status
# ─────────────────────────────────────────────────
info "Deployment status:"
echo ""
echo "  Deployments:"
kubectl get deployments -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""
echo "  Services:"
kubectl get svc -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""
echo "  Pods:"
kubectl get pods -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""
echo "  PVCs:"
kubectl get pvc -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""

echo "============================================================"
ok "Odoo 18 deployment complete!"
echo ""
echo "  Domain:    https://${ODOO_DOMAIN}"
echo "  Namespace: ${NAMESPACE}"
echo ""
echo "  Next steps:"
echo "    1. Visit https://${ODOO_DOMAIN} to access Odoo"
echo "    2. Log in with admin credentials (shown above)"
echo "    3. Install modules: website, im_livechat, hr_expense,"
echo "       point_of_sale, website_blog"
echo "    4. Install custom modules via Apps menu"
echo ""
echo "  Useful commands:"
echo "    kubectl logs -n ${NAMESPACE} deploy/odoo -c clone-addons"
echo "    kubectl logs -n ${NAMESPACE} deploy/odoo -c odoo"
echo "    kubectl port-forward -n ${NAMESPACE} svc/odoo-web-svc 8069:8069"
echo "============================================================"
