apiVersion: v1
kind: Secret
metadata:
  name: cf-secrets
  namespace: openclaw-tenant-1
type: Opaque
data:
  CF_API_TOKEN: "VmJBQndvcFJkOWxIelV2d0NzdUZvczZlYjRiaFVLWG1jQ2FkdFlwcg=="
  CF_TUNNEL_TOKEN: "ZXlKaElqb2lPV015TjJZMk1qTmxaVFU1Tm1Vd1lqWTNZbVUxTmpJMk0ySmpZakU1TnpRaUxDSjBJam9pTVRaaU1HSTNORFV0WWpGbVpTMDBNemhqTFRnd056Y3RaalpoT0dVM1lUVXdOREU0SWl3aWN5STZJbHB6VFRGbGFsUmtjSHByTlcxU1J6SkJTR3BMY3pWNE9EY3plVWt4UnpaNVNtOXpZeTlHVGt0T05WVTlJbjA9"
