apiVersion: v1
kind: ConfigMap
metadata:
  name: cf-config
  namespace: openclaw-tenant-1
  labels:
    app.kubernetes.io/part-of: openclaw-paas
data:
  CF_ACCOUNT_ID: "9c27f623ee596e0b67be56263bcb1974"
  CF_TUNNEL_ID: "16b0b745-b1fe-438c-8077-f6a8e7a50418"
  DOMAIN: "cindytech1-openclaw.woowtech.io"
