apiVersion: v1
kind: Secret
metadata:
  name: inzense-db-secret
  namespace: inzense
  labels:
    app.kubernetes.io/name: inzense-odoo
    app.kubernetes.io/component: database
stringData:
  POSTGRES_USER: "inzense"
  POSTGRES_PASSWORD: "inzense"
  POSTGRES_DB: "inzense"
type: Opaque
