apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inzense-postgres-pvc
  namespace: inzense
  labels:
    app.kubernetes.io/name: inzense-odoo
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inzense-odoo-filestore-pvc
  namespace: inzense
  labels:
    app.kubernetes.io/name: inzense-odoo
    app.kubernetes.io/component: application
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inzense-odoo-addons-pvc
  namespace: inzense
  labels:
    app.kubernetes.io/name: inzense-odoo
    app.kubernetes.io/component: application
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
