#!/bin/bash
set -euo pipefail

# =============================================================
# Hermes Smart Home Assistant - One-Click Deployment Script
# =============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFESTS_DIR="${SCRIPT_DIR}/k8s-manifests"
CF_CONFIG="${SCRIPT_DIR}/cf-config.json"
NAMESPACE="hermes"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[ OK ]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

echo "============================================================"
echo "  Hermes Smart Home Assistant - Deployment"
echo "============================================================"
echo ""

# ─────────────────────────────────────────────────
# Step 0: Validate prerequisites
# ─────────────────────────────────────────────────
info "Checking prerequisites..."

command -v kubectl >/dev/null 2>&1 || fail "kubectl is not installed."
command -v python3 >/dev/null 2>&1 || fail "python3 is not installed."

if [ ! -f "${CF_CONFIG}" ]; then
    fail "cf-config.json not found. Run the following first:\n  CF_API_TOKEN=<your-token> python3 ${SCRIPT_DIR}/init-cloudflare-hermes.py"
fi

ok "Prerequisites validated."
echo ""

# ─────────────────────────────────────────────────
# Step 1: Parse Cloudflare config
# ─────────────────────────────────────────────────
info "Reading Cloudflare configuration..."

CF_API_TOKEN=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_API_TOKEN'])")
CF_TUNNEL_TOKEN=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_TUNNEL_TOKEN'])")
CF_ACCOUNT_ID=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_ACCOUNT_ID'])")
CF_TUNNEL_ID=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['CF_TUNNEL_ID'])")
DOMAIN=$(python3 -c "import json; print(json.load(open('${CF_CONFIG}'))['DOMAIN'])")

ok "Cloudflare config loaded (domain: ${DOMAIN})"
echo ""

# ─────────────────────────────────────────────────
# Step 2: Generate PostgreSQL password if not set
# ─────────────────────────────────────────────────
if [ -z "${POSTGRES_PASSWORD:-}" ]; then
    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
    info "Generated random PostgreSQL password."
fi

# Read Minimax API key from env or prompt
if [ -z "${MINIMAX_API_KEY:-}" ]; then
    read -rp "Enter Minimax API key (or press Enter to skip): " MINIMAX_API_KEY
fi

# ─────────────────────────────────────────────────
# Step 3: Apply namespace
# ─────────────────────────────────────────────────
info "Creating namespace '${NAMESPACE}'..."
kubectl apply -f "${MANIFESTS_DIR}/00-namespace.yaml"
ok "Namespace '${NAMESPACE}' ready."
echo ""

# ─────────────────────────────────────────────────
# Step 4: Generate and apply secrets
# ─────────────────────────────────────────────────
info "Generating K8s Secrets..."

CF_API_TOKEN_B64=$(echo -n "${CF_API_TOKEN}" | base64 -w0)
CF_TUNNEL_TOKEN_B64=$(echo -n "${CF_TUNNEL_TOKEN}" | base64 -w0)
POSTGRES_PASSWORD_B64=$(echo -n "${POSTGRES_PASSWORD}" | base64 -w0)
MINIMAX_API_KEY_B64=$(echo -n "${MINIMAX_API_KEY}" | base64 -w0)

cat > "${MANIFESTS_DIR}/01-secrets.yaml" <<EOYAML
# Auto-generated by deploy.sh — DO NOT commit to version control
apiVersion: v1
kind: Secret
metadata:
  name: cf-secrets
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: hermes
type: Opaque
data:
  CF_API_TOKEN: "${CF_API_TOKEN_B64}"
  CF_TUNNEL_TOKEN: "${CF_TUNNEL_TOKEN_B64}"
---
apiVersion: v1
kind: Secret
metadata:
  name: hermes-secrets
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: hermes
type: Opaque
data:
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_B64}"
  MINIMAX_API_KEY: "${MINIMAX_API_KEY_B64}"
EOYAML

kubectl apply -f "${MANIFESTS_DIR}/01-secrets.yaml"
ok "Secrets created."
echo ""

# ─────────────────────────────────────────────────
# Step 5: Update ConfigMap with Cloudflare values
# ─────────────────────────────────────────────────
info "Updating ConfigMap with Cloudflare values..."

sed -i \
    -e "s|PLACEHOLDER_ACCOUNT_ID|${CF_ACCOUNT_ID}|g" \
    -e "s|PLACEHOLDER_TUNNEL_ID|${CF_TUNNEL_ID}|g" \
    "${MANIFESTS_DIR}/02-configmap.yaml"

ok "ConfigMap updated."
echo ""

# ─────────────────────────────────────────────────
# Step 6: Apply all manifests in order
# ─────────────────────────────────────────────────
info "Applying K8s manifests in order..."

for manifest in \
    02-configmap.yaml \
    03-pvc.yaml \
    04-postgresql.yaml \
    05-redis.yaml \
    06-hermes-agent.yaml \
    07-hermes-webui.yaml \
    08-cloudflared.yaml \
    09-ingress.yaml \
    10-network-policy.yaml; do
    if [ -f "${MANIFESTS_DIR}/${manifest}" ]; then
        info "  Applying ${manifest}..."
        kubectl apply -f "${MANIFESTS_DIR}/${manifest}"
    fi
done

ok "All manifests applied."
echo ""

# ─────────────────────────────────────────────────
# Step 7: Wait for databases to be ready
# ─────────────────────────────────────────────────
info "Waiting for PostgreSQL to be ready..."
kubectl rollout status deployment/hermes-postgresql -n "${NAMESPACE}" --timeout=120s || warn "PostgreSQL not ready yet."

info "Waiting for Redis to be ready..."
kubectl rollout status deployment/hermes-redis -n "${NAMESPACE}" --timeout=60s || warn "Redis not ready yet."

echo ""

# ─────────────────────────────────────────────────
# Step 8: Wait for application services
# ─────────────────────────────────────────────────
info "Waiting for Hermes Agent to be ready..."
kubectl rollout status deployment/hermes-agent -n "${NAMESPACE}" --timeout=180s || warn "Agent not ready yet."

info "Waiting for Hermes WebUI to be ready..."
kubectl rollout status deployment/hermes-webui -n "${NAMESPACE}" --timeout=120s || warn "WebUI not ready yet."

echo ""

# ─────────────────────────────────────────────────
# Step 9: Configure Cloudflare Tunnel route
# ─────────────────────────────────────────────────
info "Configuring Cloudflare Tunnel route..."
ROUTE_RESPONSE=$(curl -s -X PUT \
    "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/cfd_tunnel/${CF_TUNNEL_ID}/configurations" \
    -H "Authorization: Bearer ${CF_API_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "{\"config\":{\"ingress\":[{\"hostname\":\"${DOMAIN}\",\"service\":\"http://hermes-webui-svc.${NAMESPACE}.svc.cluster.local:8787\"},{\"service\":\"http_status:404\"}]}}")

ROUTE_SUCCESS=$(echo "${ROUTE_RESPONSE}" | python3 -c "import sys,json; print(json.load(sys.stdin).get('success','false'))" 2>/dev/null || echo "false")
if [ "${ROUTE_SUCCESS}" = "True" ] || [ "${ROUTE_SUCCESS}" = "true" ]; then
    ok "Cloudflare route: ${DOMAIN} → hermes-webui-svc:8787"
else
    warn "Cloudflare route config may have failed. Response: ${ROUTE_RESPONSE}"
fi
echo ""

# ─────────────────────────────────────────────────
# Step 10: Verify deployment
# ─────────────────────────────────────────────────
info "Deployment status:"
echo ""
echo "  Deployments:"
kubectl get deployments -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""
echo "  Pods:"
kubectl get pods -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""
echo "  Services:"
kubectl get svc -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""
echo "  PVCs:"
kubectl get pvc -n "${NAMESPACE}" -o wide 2>/dev/null || true
echo ""

echo "============================================================"
ok "Hermes deployment complete!"
echo ""
echo "  Domain:    https://${DOMAIN}"
echo "  Namespace: ${NAMESPACE}"
echo ""
echo "  PostgreSQL password: ${POSTGRES_PASSWORD}"
echo "  (Save this — it won't be shown again)"
echo "============================================================"
